spring:
  profiles:
    default: prod

# Default Tomcat Thread Max 200 count -> 4
server:
  tomcat:
    threads:
      max: 4

jwt:
  secretKey: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

---
spring:
  h2:
    console:
      enabled: true

  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:devdb
      username: sa
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true


---
server:
  port: 443
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      username: ${DATABASE_USER}
      password: ${DATABASE_USER_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
