name: BackEnd-CD

on: 
  push:
    # paths:
      # - 'backend/**'
    branches: [ develop , feature/**]

jobs:
  BackEnd-CD:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    defaults:
      run:
        working-directory: backend


    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_TOKEN }}
          # build-args: |
          #   DB_USER=${{ secrets.DATABASE_USER }}
          #   DB_PW=${{ secrets.DATABASE_USER_PASSWORD }}
          #   DB_URL=${{ secrets.DATABASE_URL }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          build-args: |
            JAR_FILE=backend/build/libs/*.jar
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/litarary:latest


      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy -c fly.toml